cmake_minimum_required(VERSION 3.22.1)
project(PokitLMsAndroid LANGUAGES CXX)

set(POKITLMS_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(POKITLMS_BUILD_BENCHMARK OFF CACHE BOOL "" FORCE)
set(POKITLMS_BUILD_ANDROID_APP ON CACHE BOOL "" FORCE)
add_subdirectory(${CMAKE_CURRENT_LIST_DIR}/../../../../../ ${CMAKE_CURRENT_BINARY_DIR}/pokitlms)
