name: CI

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Configure
        run: cmake -S . -B build -DPOKITLMS_BUILD_TESTS=ON

      - name: Build
        run: cmake --build build --config Release -j 2

      - name: Test
        run: ctest --test-dir build --build-config Release --output-on-failure
